spring.application.name=settleflow
spring.datasource.url=jdbc:postgresql://localhost:5432/settleflow
spring.datasource.username=settleflow
spring.datasource.password=settleflow

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
